Array Numpy

In [2]:
import numpy as np

In [3]:
mylist = [1,2,3]
type(mylist)

list

In [5]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [7]:
np.ones(shape=(3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.random.seed(101)
arr= np.random.randint(0,100,30)
print(arr)

[95 11 81 70 63 87 75  9 77 40  4 63 40 60 92 64  5 12 93 40 49 83  8 29
 59 34 44 72 19 10]


In [11]:
arr1= np.random.randint(0,100,30)
print(arr1)

[76 95 87  0 73  8 62 36 83 99 28 63  7 10 52 56 38 73 52 18 71 15 44  0
 12 17 75 79 97 93]


In [12]:
arr1.max()

99

In [13]:
arr1.argmin()

3

In [16]:
arr1.reshape((5,6))

array([[76, 95, 87,  0, 73,  8],
       [62, 36, 83, 99, 28, 63],
       [ 7, 10, 52, 56, 38, 73],
       [52, 18, 71, 15, 44,  0],
       [12, 17, 75, 79, 97, 93]])

In [18]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [19]:
row = 0
col=1

In [22]:
mat[row,col]
mat[3,5]

35

In [25]:
mat[:,2].reshape(2,5)

array([[ 2, 12, 22, 32, 42],
       [52, 62, 72, 82, 92]])

In [29]:
mat[0:3,0:3]=1
mat

array([[ 1,  1,  1,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  1,  1, 13, 14, 15, 16, 17, 18, 19],
       [ 1,  1,  1, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [30]:
newarray= mat.copy()
newarray

array([[ 1,  1,  1,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  1,  1, 13, 14, 15, 16, 17, 18, 19],
       [ 1,  1,  1, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [33]:
newarray[0:4,:]=99
newarray

array([[99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])